import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MainLayout from "@/components/MainLayout";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='ko'
      className={`${pretendard.variable} scroll-smooth`}
      suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <main className='flow content-grid'>
            <MainLayout>{children}</MainLayout>
          </main>
          <Footer />
          <Toaster position='top-center' />
        </Providers>
      </body>
    </html>
  );
}
