import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/Navbar";
import Logo from "./components/Logo";

const inter = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${inter.variable}`}>
      <body className="max-w-5xl mx-auto min-h-screen">
        <header className="flex justify-between items-center">
          <Logo />
          <Navbar />
        </header>
        <main className="h-full pb-6">{children}</main>
        <footer className="fixed bottom-0 flex justify-center items-center w-full left-0 space-x-2 h-10 bg-white">
          <p>
            © 2023.
            <span className="text-md font-bold"> 문지웅 </span>
            | All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
