import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Footer, Header } from "./components";

const inter = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${inter.variable} scroll-smooth`}>
      <body className="max-w-5xl mx-auto min-h-screen">
        <Header />
        <main className="h-full pb-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
